In [1]:
import pandas as pd
import numpy as np

In [ ]:
#make a new column for episode count    - > done
#make a new column for time stamp       - > done
#which anime has the highest score      - > done
#give me top 5 highest scoring anime    - > done
#which anime has the highest episode count -> done
#animes with top 5 episode count        - > done
#which is the longest running anime     - > done

In [2]:
df = pd.read_csv('anime.csv')

In [3]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
df.loc[4]['Title']

'Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview'

In [7]:
df.isnull().sum()

Rank     0
Title    0
Score    0
dtype: int64

In [8]:
def extract_episodes(txt):
    check = False
    data = ""
    for i in txt:
        if(i == ')'):
            check = False
            return data
        if check == True: 
            data = data + i 
        if i == '(':
            check = True

In [9]:
df["Episodes"] = df["Title"].apply(extract_episodes)

In [17]:
df["Episodes"] = df["Episodes"].str.replace(" eps","")

In [25]:
df['Episodes'] = df['Episodes'].astype(int)

In [24]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [30]:
def extract_time(txt):
    check = False
    data = ""
    for i in txt:
        if check == True:
            data += i
        if i == ')':
            check = True
        if len(data) == 19:
            return data
    return data

In [31]:
df["Total_time"] = df["Title"].apply(extract_time)

In [33]:
df["Total_time"].head()

0    Apr 2009 - Jul 2010
1    Apr 2011 - Sep 2011
2    Oct 2022 - Dec 2022
3    Apr 2015 - Mar 2016
4    Apr 2019 - Jul 2019
Name: Total_time, dtype: object

In [34]:
df.head()

,Rank,Title,Score,Episodes,Total_time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [39]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1  # +1 to include the starting month
    except:
        return None

df['Months'] = df['Total_time'].apply(calculate_total_months)

In [40]:
df.head()

,Rank,Title,Score,Episodes,Total_time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [45]:
df[df['Score'] == df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: object

In [47]:
df['Title'][1]

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [ ]:
def views(txt):

In [51]:
df[df['Episodes'] == df['Episodes'].max()]['Title']

15    GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...
Name: Title, dtype: object

In [59]:
df[df["Months"] == df["Months"].max()]['Title']

11    Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...
Name: Title, dtype: object

In [60]:
df.head()

,Rank,Title,Score,Episodes,Total_time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [71]:
sorted_idx = np.argsort(-df['Score'])

In [72]:
counter = 1
for i in sorted_idx:
    if counter > 5:
        break
    print(f"{counter} : score -> {df["Score"][i]} and title : {df["Title"][i]}")
    counter += 1

1 : score -> 9.1 and title : Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
2 : score -> 9.07 and title : Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
3 : score -> 9.06 and title : Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members
4 : score -> 9.06 and title : Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members
5 : score -> 9.05 and title : Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview

In [73]:
sorted_idx_ep = np.argsort(-df['Episodes'])

In [74]:
counter = 1
for i in sorted_idx:
    if counter > 5:
        break
    print(f"{counter} : Episodes -> {df["Episodes"][i]} and title : {df["Title"][i]}")
    counter += 1

1 : Episodes -> 64 and title : Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview
2 : Episodes -> 24 and title : Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members
3 : Episodes -> 13 and title : Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members
4 : Episodes -> 51 and title : Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 members
5 : Episodes -> 10 and title : Shingeki no Kyojin Season 3 Part 2TV (10 eps)Apr 2019 - Jul 20192,146,679 membersManga StoreVolume 1€10.99Preview